freeCodeCamp/Developer_Quiz_Site

.github/workflows/deploy.yml
=> feat(tools): add deployment workflow

src/data/full-quiz.js
while it's a new branch that mean it wasn't there 
Checklist:
Closes #XXXXX
=> update answer for switching to a new branch in Git

src/data/full-quiz.js
=> fix: fixed typo in quiz question

src/components/QuizModal.jsx, src/components/QuizTemplate.jsx, src/data/modal-responses.js, src/stylesheets/App.css
Checklist:
New feature:
I added an array of modal responses when a user gets an answer correct or incorrect.
=> feat: adding random modal responses for correct & incorrect quiz answers

src/data/full-quiz.js
Checklist:
Editing Python quiz question.
=> fix: editing python quiz question on attributes

src/components/Results.jsx
Checklist:
I added a condition to the results page that displays a perfect score message if the user gets all of the quiz questions correct.
=> feat: adding perfect score message in results page

src/data/full-quiz.js
Checklist:
Fixed the incorrect answer in linux quiz question and changed answer to the `uname -o` command.
=> Fix: updating linux question on uname commands

src/data/full-quiz.js
=> Add new JavaScript quiz questions

src/data/full-quiz.js
=> Added new Javascript quiz questions #14

src/data/full-quiz.js
Checklist:
Updating distractor answers for a couple of JavaScript questions.
=> fix: updating distractor answers for JavaScript questions

src/data/full-quiz.js
=> Add more JavaScript quiz questions to Developer_Quiz_Site

src/data/full-quiz.js
Checklist:
Reformatting json file for the quiz questions.
=> Fix: reformatting quiz file

src/data/full-quiz.js
Reverts freeCodeCamp/Developer_Quiz_Site#25
=> Revert "Fix: reformatting quiz file"

src/data/full-quiz.js
=> Added new Javascript quiz questions ( issue #14 )

src/data/full-quiz.js
=> fix: fixing formatting issues for quiz file

src/components/QuizModal.jsx, src/data/full-quiz.js
Checklist:
Adding two CS questions to quiz file.
=> feat:adding cs questions

src/data/full-quiz.js
=> New Javascript Question added

src/data/full-quiz.js
=> Added a new Python question

src/data/full-quiz.js
=> fix: fixed typo for array question in quiz file

src/components/Navbar.jsx
=> Added target_blank attribute in navbar logo.

src/components/Navbar.jsx
=> fix: adding rel noreferrer to navbar link

src/data/full-quiz.js
=> Add JavaScript questions

src/data/full-quiz.js
Adding SQL quiz questions #17  - Added SQL Wildcard Question
Checklist:
Closes #XXXXX
=> added sql wildcard question

src/components/Button.jsx
- Added `useMemo` to handle button classes properly 
- Optimized and cleanup the Button component located at ` src\components\Button.jsx`
=> Optimized  the button component

src/data/full-quiz.js
Checklist:
- [ X ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ X ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)
=> Add new JavaScript questions

src/data/full-quiz.js
added a question on the triple-equals in Javascript, ref to freecodecamp website
Checklist:
Closes #XXXXX
=> triple-equal-operator question

.github/workflows/deploy.yml, .github/workflows/lint.yml
=> feat: add linting to CI

src/data/full-quiz.ts
=> chore: standardize prefix language of questions

src/data/full-quiz.ts
=> chore: update chat link

src/data/full-quiz.ts
The answer of Discord is technically not self-hosted.
Checklist:
Closes #XXXXX
=> chore: be more precise with chat question

.gitattributes, .husky/pre-commit, package-lock.json, package.json, src/components/Button.tsx
I found the information on https://www.inkoop.io/blog/setup-eslint-for-react-with-prettier-pre-commit-and-vscode/
Hopefully it'll work nicely.
Checklist:
Closes #77
Pre-commit was intimidating but pretty-quick seems pretty easy? I know it's not exactly what you want , but it could work maybe?
=> chore: setting up pre-commit hooks

src/data/full-quiz.ts
=> Added few OOP based questions.

src/data/full-quiz.ts
Adding one vim editor-based question. 
Ref: Added Vim Question - visual mode #90
=> Added Vim Question - visual mode

src/data/full-quiz.ts
Checklist:
Over the years , I never really got into gulp and grunt. When it was time for me to take on applications on my own, I realized npm scripts was the way to go for me. I'm happy to see that I made the right choice.
=> Chore: Create a question related to npm scripts

src/__test__/Data.test.tsx, src/data/full-quiz.ts
=> Chore: Add a data driven test to make sure all questions display correctly

src/data/full-quiz.ts
Checklist:
Added question for a simple JS method that's frequently used when dealing with user input fields.
=> chore: added js method question

src/data/full-quiz.ts
=> fix: correcting syntax issue for string output for Python question

README.md
=> Update README.md to fix the quiz file link

.github/ISSUE_TEMPLATES/bugs.yml, .github/ISSUE_TEMPLATES/config.yml, .github/ISSUE_TEMPLATES/documentation.yml, .github/ISSUE_TEMPLATES/features.yml, .github/ISSUE_TEMPLATES/general.yml
=> chore: adding issue templates in preparation for hacktoberfest 

src/data/full-quiz.ts
In reference to the article below,
https://www.freecodecamp.org/news/white-hat-black-hat-red-hat-hackers/ , I've added 2 questions with respect to Black Hat and White Hat Hackers.
Checklist:
=> feat : Added few Cybersecurity related Quiz questions

src/data/full-quiz.ts
Checklist:
In reference to the article below,
https://www.freecodecamp.org/news/agile-methods-and-methodology-for-beginners/, I've added 2 questions regarding Agile.
=> feat: Added two Agile questions

src/components/Questions.tsx
Checklist:
Closes #94
I am going to be playing the size values sooner than later. I just wanted to get it started.
=> feat: Question Number at the top

src/data/full-quiz.ts
Checklist:
As per commit message, just added four questions related to Agile, relates to #103
=> feat: Add four Agile questions

src/data/full-quiz.ts
=> feat: adding two CS related quiz questions

CONTRIBUTING.md, README.md
I updated the contributing file to include more beginner friendly instructions. 
Checklist:
=> docs: updating contributing file and readme

CONTRIBUTING.md
=> docs: updating contributing file

src/data/general-cs-quiz.ts
=> Added a new computer science question.

README.md
=> docs: Added Three New Quiz Categories to README

src/data/javascript-quiz.ts
Checklist:
Adds to #14 
Question is about unary operator.
=> Added js quiz question

src/data/git-quiz.ts
=> Added a new question to Git Quiz (Rename Branch)

src/data/agile-quiz.ts, src/data/html-quiz.ts, src/data/information-technology-quiz.ts, src/data/security-quiz.ts
Checklist:
Closes #XXXXX
Number of questions added in each domain is as follows:
Agile-quiz: 1
Information-Technology-quiz: 1
html-quiz: 1
security-quiz: 2
=> Add: 5 questions 

src/data/python-quiz.ts
Checklist:
#15 
Adding a question related to Dunder methods in python-quiz.ts file.
Also, I would like to make this contribution for the Hacktoberfest event.
Thank you!
=> Added a question in python-quiz.ts

src/data/javascript-quiz.ts
=> Added a new JavaScript quiz question

src/data/javascript-quiz.ts
=> New javascript question added (typeof Null)

src/data/linux-quiz.ts
#16 Adding one question based on Linux System. Ques is about printenv, command helping in printing environment variables.
=> Added Linux Ques-printenv#16

src/data/javascript-quiz.ts
I have added a Javascript Question related to the scope used in javascript.
Checklist:
I have added a question on the scope used in Javascript.
I have written its explanation and linked an freeCodeCamp article
=> Javascript Question Added

src/data/linux-quiz.ts
=> chore: adding linux questions

src/data/javascript-quiz.ts
=> added js question of DOM styling

src/data/javascript-quiz.ts
Checklist:
This PR adds a new Javascript question related to Closures. It is related to https://github.com/freeCodeCamp/Developer_Quiz_Site/issues/14
=> Adds javascript question related to closures

src/data/security-quiz.ts
=> added a new security question

src/data/python-quiz.ts
On the issue of #15, adding questions based on Explicit type conversion from Python.
=> Adding Ques based on Python Explicit type coversion

src/data/python-quiz.ts
Checklist:
Closes #XXXXX
Added a question related to Creating Packages in python, putted 3 distractors, a proper explanation and a link to freecodecamp's blog.
=> New Question related to Creating Packages (Python)

src/data/security-quiz.ts
=> chore: adding new question for security quiz

src/data/javascript-quiz.ts
Ref to issue #14 , adding one JavaScript question based on innerHTML DOM topic.
=> Adding Ques JavaScript - innerHTML

src/data/sql-quiz.ts
=> new question about now() function for SQL quiz

src/data/git-quiz.ts, src/data/sql-quiz.ts
=> chore: adding SQL and Git questions

src/data/security-quiz.ts
Checklist:
Closes #XXXXX
More exciting quiz questions in the security category are included in this PR.
Thanks!
=> Chore: Adding questions in security-quiz.

src/data/quality-assurance-quiz.ts
=> Add QA quiz questions about types of testing

src/data/javascript-quiz.ts
=> chore: adding javascript question on typeof operator

src/data/git-quiz.ts, src/data/sql-quiz.ts
=> Adding new SQL question

src/data/python-quiz.ts
=> Added two new questions for python quiz

src/data/sql-quiz.ts
=> Add SQL Quiz Question "How to Access All Column Names"

src/data/javascript-quiz.ts
Ref to issue #14. Added one quiz question about the addEventListener() method based on Event Handling and another question about Type coercion in Javascript.
Checklist:
=> Adding Question Javascript - eventListener

src/data/javascript-quiz.ts
=> Added a new JavaScript Question

src/data/linux-quiz.ts
Checklist:
Closes #XXXXX
Added questions for netstat, kill and crontab commands in linux.
=> Added netstat, kill and crontab commands in linux

src/data/python-quiz.ts
=> Added two questions on tuple

src/data/agile-quiz.ts
Ref to issue #103. Added three questions on "waterfall development", "kanban" and "story" based on agile.
Checklist:
=> Added questions on agile-quiz

src/data/javascript-quiz.ts
* add javascript question to javascript quiz
* update src/data/javascript-quiz.ts
=> Adding javascript question on .push() method

src/components/Button.tsx
* Custom Button component (<Button />) is memoized.
* Since the <Button /> component is used in Questions page, for each question, <Button /> component re-renders for no reason, eventhough it's prop is not changing.
=> Memoize <Button /> Component

src/data/security-quiz.ts
=> Added a security question

src/data/javascript-quiz.ts
Checklist:
Related to issue #14 
Potentially for "general CS" but time complexity is also useful to introduce in JavaScript-focused contexts.
=> Added JavaScript time complexity question

src/data/javascript-quiz.ts, src/data/sql-quiz.ts
=>  add MYSQL question from line number 380 to 390

src/data/html-quiz.ts, src/data/security-quiz.ts
Checklist:
Closes #XXXXX
This PR adds more exciting questions on the HTML category.
Thanks!
=> Chore: adding HTML questions.

src/data/security-quiz.ts
Checklist:
This change introduces two security questions on the topic of homomorphic encryption.
=> Issue #104: Adding security questions to dev quiz site

src/data/javascript-quiz.ts
* Add Javascript question to Javascript quiz
* update src/data/javascript-quiz.ts
=> Added Javascript question on variable hoisting

src/data/css-quiz.ts, src/data/javascript-quiz.ts
=> added javascript questions on type coercion and falsy values

src/data/security-quiz.ts, src/data/sql-quiz.ts
=> Two new questions about sql injection security.alvaro tab

.dockerignore, CONTRIBUTING.md, Dockerfile, package.json
Checklist:
Closes #189 
The following PR introduces an option for contributors to test their changes locally through Docker. 
Apart from solving the "it worked on my machine", containerization is "hot" in the industry with cloud computing and microservices and this will allow interested contributors to gain experience with the tooling. 
The PR can be testing by first building the image with: `docker build -t developer-quiz-site .` followed by `docker container run --rm -it -p 3000:3000 developer-quiz-site`. 
Visiting port 3000 on localhost should show the quiz site up-and-running. 🚀🐳
=> Issue #189: Feature introduced - containerized deployment through Docker for contributors

src/data/javascript-quiz.ts
Checklist:
- [ x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)
=> Javascript quize - added two new questions

src/data/general-cs-quiz.ts
=> fix(general-cs-quiz.ts) : added new question

src/data/sql-quiz.ts
=> add Question in sql-quiz.ts from line number 391 to 401

src/data/general-cs-quiz.ts, src/data/python-quiz.ts, src/data/sql-quiz.ts
Checklist:
Closes #XXXXX
This PR adds more exciting questions on SQL, Python and general CS categories.
Thanks!
=> chore: SQL/Python questions added

src/data/security-quiz.ts
=> chore: adding security questions

src/data/python-quiz.ts
=> chore: Added  one new python question based on .join method

src/data/python-quiz.ts
=> Adding a question on command-line arguments in Python

src/data/sql-quiz.ts
=>  two sql Questions added

src/data/security-quiz.ts, src/data/sql-quiz.ts
=> Added sql question

src/data/javascript-quiz.ts
=> 2 js questions added in javascript-quiz.ts

src/data/security-quiz.ts
Checklist:
I corrected the spelling in a few of the questions and answers and followed up with a little research on key encryption: https://www.cloudflare.com/learning/ssl/what-is-asymmetric-encryption/
=> Chore: Fix minor spelling issues

src/data/agile-quiz.ts, src/data/general-cs-quiz.ts, src/data/html-quiz.ts, src/data/javascript-quiz.ts, src/data/linux-quiz.ts, src/data/security-quiz.ts
=> add questions to the general CS quiz

src/data/javascript-quiz.ts
=> Added a JavaScript question about classList

src/data/linux-quiz.ts
=> Four Linux Question added

src/data/security-quiz.ts
=> Added new security questions about steganograpy and RSA

src/data/general-cs-quiz.ts
=> Added 5 general computer science questions

src/data/javascript-quiz.ts
=> chore: adding JS question on undeclared variables and typeof operator

src/data/javascript-quiz.ts
=> Added some new questions to JavaScript, topic: arrays

src/data/javascript-quiz.ts
=> Added a question on event loop in js question upload

src/data/general-cs-quiz.ts
=> Added A Question on Merge Sort in Computer Science Questions

src/data/general-cs-quiz.ts
=> Added questions to General section

src/data/javascript-quiz.ts
=> question about basic group of data types in Javascript

src/data/security-quiz.ts
=> Added a question about OWASP Top 10

src/data/quality-assurance-quiz.ts
=> Add a question regarding the importance of software tests.

src/data/python-quiz.ts
=> chore: adding 2 python questions

src/data/linux-quiz.ts, src/data/python-quiz.ts
=> added a linux related question 

src/data/python-quiz.ts
Checklist:
#15 
Added questions related to os module and cmd module in python.
=> added questions in python-quiz.ts

src/data/linux-quiz.ts
=> Added new linux questions

src/data/general-cs-quiz.ts
Checklist:
Closes #XXXXX
Changes include:
* 4 questions related to data structures and algorithm
* 1 general question
=> Added 5 questions related to Computer Science (4 algorithms related and 1 general)

src/data/general-cs-quiz.ts
=> Added a question on stacks

src/data/javascript-quiz.ts
=> add javascript quiz preventDefaut in javascript-quiz.ts

src/data/quality-assurance-quiz.ts
Checklist:
Adds to #102  
Question covers exhaustive testing.
=> Added QA Quiz Question

src/data/javascript-quiz.ts
=> Added a question in javascript-quiz.ts

src/data/javascript-quiz.ts
=> Javascript question about data type

src/data/general-cs-quiz.ts
=> Added new questions to general-cs-quiz.ts

src/data/quality-assurance-quiz.ts
=> added regression test question to the qa quiz

src/data/general-cs-quiz.ts, src/data/python-quiz.ts
=> Added Questions in python-quiz.ts and general-cs-quiz.ts

src/data/general-cs-quiz.ts, src/data/git-quiz.ts
=> Add questions to the git quiz

src/data/agile-quiz.ts
=> Add agile question about sprint cancelling

src/data/security-quiz.ts
=> New security question is added

src/data/javascript-quiz.ts
=> add a question to javascript file

src/data/css-quiz.ts
=> added css questions

src/data/agile-quiz.ts
Added new question about agile methods, more specifically about Story Points.
Checklist:
Closes #XXXXX
=> Added new question about agile methods

src/data/python-quiz.ts
=> Add a quiz question in `python-quiz.ts`

src/data/linux-quiz.ts
=> added quiz question in linux-quiz.ts

src/data/sql-quiz.ts
=> Add a question regarding table relationships.

src/data/python-quiz.ts
=> chore: Added another question in `python-quiz.ts`

src/data/general-cs-quiz.ts
=> Added stack question

src/data/javascript-quiz.ts
=> feat: add new javascript quiz

src/data/freecodecamp-quiz.ts
=> added a question in freecodecamp-quiz

src/data/sql-quiz.ts
=> Added a SQL question based on update query.

src/data/javascript-quiz.ts
=> Added a javascript question based on loop through arrays

src/data/python-quiz.ts
=> Added a python question based on complex number in python

src/data/javascript-quiz.ts
=> Add a  new JavaScript quiz question

src/data/javascript-quiz.ts
=> added a javascript question

src/data/linux-quiz.ts
=> Added a linux question

src/data/python-quiz.ts
Checklist:
- [+] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [+] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)
Closes #XXXXX
=> Add a Quiz in Python Quiz list

src/data/git-quiz.ts
=> added a git question

src/data/javascript-quiz.ts
=> Js question2

src/data/javascript-quiz.ts
=> feat: add javascript question

src/data/python-quiz.ts
=> Add a python quiz question based on map function

src/data/git-quiz.ts
=> feat: add two new git quiz question

src/data/agile-quiz.ts
Checklist:
Closes #XXXXX
Addes quesiton to the agile quiz about the five scrum values.
=> Add agile question about Scrum values

src/data/python-quiz.ts
=> adding python getsizeof question

src/data/agile-quiz.ts
=> Add Agile Timeboxing Question

src/data/python-quiz.ts
=> Add question for python map function regarding input of n spaced intigers

src/data/general-cs-quiz.ts
=> Added a computer science quiz question regarding generation of computers

src/data/javascript-quiz.ts
=> added two data types javascript questions

src/data/javascript-quiz.ts
=> added one questions in javascript-quiz.ts

src/data/python-quiz.ts
=> Added a python quiz question on reversing a list.

src/data/agile-quiz.ts, src/data/python-quiz.ts
Checklist:
Closes #XXXXX
Issue - #103
=> Add agile priority question

src/data/css-quiz.ts, src/data/general-cs-quiz.ts
=> Add css rgb question

src/data/agile-quiz.ts
Checklist:
Closes #XXXXX
Issue: #103
=> Add Agile question to quiz site

src/data/javascript-quiz.ts
This is a program based question.
Checklist:
Closes #XXXXX
=> Added a new Question in js Quiz(related to string/slice function.

src/data/html-quiz.ts
=> Added a html question on empty tag

src/data/python-quiz.ts
Both are related to sorted method.
Checklist:
Closes #XXXXX
=> Bitwise operators in Python

src/data/python-quiz.ts
added a python mcq related to string concatenation.
Checklist:
Closes #XXXXX
=> added a python question

src/data/python-quiz.ts
Add a question about the counting set bits.
Checklist:
Closes #XXXXX
=> Count the set bits in an integer.

src/data/sql-quiz.ts
=> Added a sql questions on primary key

src/data/linux-quiz.ts, src/data/modal-responses.ts
=> Add new response for correct and incorrect answer's

src/data/javascript-quiz.ts
=> Add Javascript question

src/data/sql-quiz.ts
It is about View concept in SQL.
Checklist:
Closes #XXXXX
=> Add a SQL question

src/data/python-quiz.ts
=> Added python re question to python-quiz.ts

src/data/javascript-quiz.ts
Added a new question related to double and triple equal sign comparison operator.
Checklist:
Closes #XXXXX
=> Added a new question .

src/data/linux-quiz.ts
Checklist:
Adds to #16 
The added question is regarding the find command of Linux.
=> Added Linux Quiz Question

src/data/quality-assurance-quiz.ts
Checklist:
Adds to #102 
The added question is regarding system testing.
=> Added System test QA Quiz Question

src/data/javascript-quiz.ts
Added a new quiz in the JavaScript section
Checklist:
Closes #XXXXX
=> Added a JS quiz  to javascript-quiz.ts

src/data/python-quiz.ts
Added a new question related to sets and lists
Checklist:
Closes #XXXXX
=> Added a new question

src/data/git-quiz.ts
=> Add questions to git-quiz.ts (git cherry-pick and git tag)

src/data/javascript-quiz.ts
=> add JS question

src/data/accessibility-quiz.ts, src/data/agile-quiz.ts
Checklist:
Closes #XXXXX
I added a question about accessibility tools under the accessibilityQuiz section.
=> add question about accessibility tools under the A11y quiz

src/data/linux-quiz.ts
=> Added some linux questions

src/data/javascript-quiz.ts
=> chore: adding question for event bubbling

src/data/javascript-quiz.ts
=> adding JS question for Math.floor

src/data/javascript-quiz.ts
=> adding question for localStorage

src/data/accessibility-quiz.ts
Added a question about semantic html for accessibility
Checklist:
Closes #XXXXX
=> Added a new question in web accessibility section

src/data/general-cs-quiz.ts
=> Added a new question on general CS section

src/data/information-technology-quiz.ts, src/data/security-quiz.ts
Checklist:
Closes #XXXXX
Issue #104
=> Add New Ques in Security Quiz

src/data/accessibility-quiz.ts
Checklist:
Adds to #374 
Hey, so glad to see this as a new quiz category! I'm happy to add more questions but want to do things in the way that's easiest for the maintainers to keep up with. Is one question per PR the way to go or would multiple at once be a better option?
=> Added Accessibility Question

src/data/javascript-quiz.ts
=> add a javascript question

public/index.html, src/components/Results.tsx
=> Enhancement: Add the ability to share from the results screen

src/data/accessibility-quiz.ts
=> Add 4 new accessibility quiz questions

src/data/javascript-quiz.ts
-added a missing answer to Distractor2 which was an empty string before.
{
Question: "In JavaScript, what will the following code return: typeof a?",
Answer: "undefined",
Distractor1: "string",
Distractor2: "object",
Distractor3: "number",
Explanation:
"In JavaScript, if you use the typeof operator on an undeclared variable then it will return undefined. ",
Link: "https://www.freecodecamp.org/news/javascript-typeof-how-to-check-the-type-of-a-variable-or-object-in-js/",
},
Checklist:
Closes #399
=> fix: missing answer for javascript question

src/data/accessibility-quiz.ts
=> Added a new question on web accessibility

src/data/sql-quiz.ts
Checklist:
-[ ] I have read  https://www.w3schools.com/mysql/func_mysql_round.asp -[ ]  My pull request has a descriptive title (not a vague title like Update index.md)
Checklist:
Closes #XXXXX
=>  added one question regarding round function in sql-quiz.ts.

src/data/javascript-quiz.ts
=> Added Nullish Coalescing Operator question in Javascript

src/data/accessibility-quiz.ts
=> Add HTML lang attribute question to accessibility quiz

src/data/css-quiz.ts, src/data/javascript-quiz.ts
=> Added a new css question

src/data/agile-quiz.ts
=> Add story points question to agile quiz

src/__test__/Data.test.tsx
Checklist:
Closes #XXXXX
There was a question that seemed to fail one of my data inspections: "In Linux, there are three types of users: user, group and other.", "Question": "Which set among the following is the correct set of three types of Linux file users". It seemed to be lacking a link. I didn't seem to notice any other broken questions yet however.
=> Chore: Test Question Length

src/data/javascript-quiz.ts
=> Event loop precedence

src/data/javascript-quiz.ts
=> add NaN js question

src/data/python-quiz.ts
Added question on python kindly review it and merge it.
Checklist:
Closes #XXXXX
=> Updated python-quiz.ts

src/components/HeroSection.tsx, src/stylesheets/HeroSection.css
=> fix: refactored the HeroSection component and the styles

src/data/general-cs-quiz.ts
=> Added question in general cs questions of an inplace sorting algorithm

src/data/linux-quiz.ts
=> added a question in linux-quiz.ts

src/data/accessibility-quiz.ts
=> add 3 more questions to accessibility quiz

src/data/html-quiz.ts
Added a question based on the application of href tag in an html document code.
Closes #XXXXX
Please add a **hacktoberfest accepted** tag after merged.
Thanks for the opportunity.
=> Added a question to general-html-quiz.ts

src/data/linux-quiz.ts, src/stylesheets/HomepageRow.css
=> added new question on chmod in linux

src/data/python-quiz.ts
=> Added 3 python questions

src/data/accessibility-quiz.ts, src/data/agile-quiz.ts
=> a11y question about lang attribute

src/data/python-quiz.ts
Checklist:
#15 
I added a Question Related to Set in python.
Thank You
=> Adding Question in Python Quiz

src/data/agile-quiz.ts, src/data/sql-quiz.ts
=> Adding sql quiz questions

src/data/agile-quiz.ts, src/data/sql-quiz.ts
=> added-agile-questions

src/data/javascript-quiz.ts
=> Added Javascript questions

src/data/information-technology-quiz.ts
=> added question on network models

src/data/git-quiz.ts
=> Added a new question on git integrity in git-quiz.ts

src/data/git-quiz.ts
=> Add question to git quiz about stash

src/data/security-quiz.ts
=> adde question on the attack model

src/data/javascript-quiz.ts
=> New JavaScript question about Promises

src/data/agile-quiz.ts
=> add new Agile question

src/data/linux-quiz.ts
=> First contribution changes made to linux-quiz.ts

src/data/accessibility-quiz.ts
=> Added a new question to the accessibility section

src/data/javascript-quiz.ts
Checklist:
Question: "In JavaScript, what will be the return value of console.log(new String('Hello, world!') === 'Hello, world!')?"
I have tested by running the project and see the output.
=> Add JavaScript quiz - strict value comparison example question

src/data/security-quiz.ts
=> Added question on cryptographic hash in security-quiz.ts

src/data/linux-quiz.ts
=> Added a question to linux-quiz.ts

src/data/javascript-quiz.ts
=> Add JavaScript export question 

src/data/linux-quiz.ts
=> chore: added one question based on ls -d command in linux-quiz.ts

src/data/python-quiz.ts
=> added python quiz question

src/data/javascript-quiz.ts
Checklist:
Closes #XXXXX
Added a JS Question about Asynchronous Functions.
=> feat: Add a JS Question

src/data/linux-quiz.ts
=> chore: added one question based on awk command in linux-quiz.ts

src/data/javascript-quiz.ts
=> Added question to javascript-quiz.ts

src/data/information-technology-quiz.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1BRlCuAQh8ykjHqdWEJaszkpYWL2Zx4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=G5A8Yzw)
Added flush DNS command question to the IT quiz.
Checklist:
Closes #XXXXX
=> Add DNS command question to IT quiz

src/data/sql-quiz.ts
=> Added question in sql.quiz

src/data/linux-quiz.ts
=> Added questions in linux-quiz.ts src/data directory

src/data/accessibility-quiz.ts
Checklist:
Closes #XXXXX
Excited to contribute and happy to accept changes!
=> chore: add accessibility question to quiz

src/data/javascript-quiz.ts
Checklist:
Adds to #14 
Question is about lastIndexOf() method.
=> added lastIndexOf() javascript question

src/data/general-cs-quiz.ts
=> added one question related binary search vs linear search.

src/data/html-quiz.ts
=> added one question about hypertext in html-quiz.ts

src/data/css-quiz.ts
-  [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)
=> Added a question to css-quiz.ts

src/data/linux-quiz.ts
=> added one question about  vim editor in linux-quiz.ts

src/data/css-quiz.ts
=> Add a CSS question about CSS stroke property

src/data/linux-quiz.ts
Added Linux questions for quizzing question set.
Signed-off-by: Yashasvi Chaurasia <yashasvi12977@gmail.com>
Checklist:
=> chore: added linux Question

src/data/javascript-quiz.ts
Checklist:
#14 
Added 2 questions about what happens when you use `+` and `-` when one is a string (with the contents of a number) and the other is an integer.
For the links I want to use [this](https://javascript.info/operators#string-concatenation-with-binary) but I cant figure out how to link to specific examples.
=> Added JS questions about `+` and `-` when the contents of strings are numbers

src/data/python-quiz.ts
Checklist:
Closes #15 
I added a Question Related to String in python.
Thank You
=> Adding New Question in Python Quiz

src/data/agile-quiz.ts
=> Added Agile quiz question

src/data/javascript-quiz.ts
=> Added new js question related to data types

src/data/git-quiz.ts
Added git question to git quizzing question set
Signed-off-by: Yashasvi Chaurasia <yashasvi12977@gmail.com>
Checklist:
=> chore: added git question

src/data/javascript-quiz.ts
Basic difference between indexOf() and search() string method in js
Checklist:
Closes #XXXXX
=> Added new question in js

src/data/accessibility-quiz.ts
Add question on autocomplete attribute
Checklist:
On issue #374 
Thank You!
=> Add more accessibility question

src/data/css-quiz.ts
=> Added Attribute  Selector question in css-quiz.ts

src/data/general-cs-quiz.ts
=> Adding a question on sorting algorithms

src/data/javascript-quiz.ts
=> Added javascript question about Math.random()

src/data/javascript-quiz.ts
Added a js question related to js string methods.
Checklist:
Closes #XXXXX
=> Added a new question in js

src/data/general-cs-quiz.ts
Sorting questions
Checklist:
Closes #XXXXX
=> Added CS questions

src/data/python-quiz.ts
=> Added one question regarding python functions in python-quiz.ts

src/data/general-cs-quiz.ts
Checklist:
#15 
I added a Question Related to the Time Complexity of Bubble Sort in the general cs Quiz.
Thank You
=> Add new Question in general_cs_quiz

src/data/javascript-quiz.ts
Checklist:
#14 
We have a question about primitive data types so why no composite types as well?
=> Added JS question about composite data types

src/data/general-cs-quiz.ts
Checklist:
#15 
I added a Question Related to Time Complexity in the general CS quiz.
Thank You
=> chore: adding question for time complexities in CS quiz

src/data/accessibility-quiz.ts
=> new question_motor

src/data/general-cs-quiz.ts
=> Added new question

src/data/general-cs-quiz.ts
=> added new question in general-cs-quiz.ts

src/data/javascript-quiz.ts, src/data/linux-quiz.ts
=> Question about Object data Fetching methods

src/data/general-cs-quiz.ts
=> Added new question : general-cs-quiz.ts

src/data/sql-quiz.ts
=> Added a new sql question based on aggregate functions

src/data/javascript-quiz.ts
=> Add the Question in JS Guess the Sum of expression?

src/data/git-quiz.ts
=> Add Git Question how to stage all changes with one line of code

src/data/html-quiz.ts
=> Added a HTML question

src/data/git-quiz.ts
=> Add a Question about how a commit message should be ?

src/data/git-quiz.ts
=> Add Question how to log previous commits in git

src/data/javascript-quiz.ts, src/data/linux-quiz.ts
=> Add Linux question

src/data/linux-quiz.ts
=> Add a Linux question about long listing

src/data/linux-quiz.ts
=> Add a linux question of how to display the content of the files

src/data/linux-quiz.ts
=> Add a linux question about how to list last lines of a file

src/data/linux-quiz.ts
=> Add linux question to create a new file and open in vi editor

src/data/accessibility-quiz.ts
Added a quiz question to the accessibility quiz
Checklist:
Closes #XXXXX
=> Modified accessibility-quiz.ts to add a quiz question

src/data/git-quiz.ts
Checklist:
Closes #XXXXX
Git question about unstaging a staged file using git cli
=> Chore: Added a question for unstaging files using git

src/data/git-quiz.ts
Checklist:
Closes #XXXXX
I have added a question on the default text editor used in git bash
=> Added Git Question

src/data/sql-quiz.ts
=> Added a new sql question regarding database deletion

src/data/general-cs-quiz.ts, src/data/python-quiz.ts
Checklist:
Hello Sir/Miss,
I added two new questions (one on the Computer Science topic and the second one on the Python topic). Thanks for the opportunity of being able to contribute to this repo.
I hope you like them!
=> New Computer Science(1) and Python(1) questions

src/data/general-cs-quiz.ts
=> Added a new general cs question about static vs dyanamic typed languages

src/data/accessibility-quiz.ts
=> Added an accessibility question to the quiz

src/data/quality-assurance-quiz.ts
=> Added quality assurance and testing questions

src/data/linux-quiz.ts
=> Add a Linux Question

src/data/linux-quiz.ts
=> Add a linux Question About Cat command

src/data/general-cs-quiz.ts, src/data/javascript-quiz.ts
=> Update javascript-quiz.ts With FizzBuzz Question

src/data/javascript-quiz.ts
=> Fixed the typos on the Javascript question about querySelector

src/data/javascript-quiz.ts, src/stylesheets/App.css, src/stylesheets/Button.css, src/stylesheets/HeroSection.css, src/stylesheets/HomepageRow.css, src/stylesheets/Navbar.css
Checklist:
Closes #14 
Added two JavaScript quiz questions
Reorganized the position of properties so that they are not randomly located, but grouped according to their type. Refactored some parts of the code by merging the identical and repeated code in the same file, and removing the unnecessary ones, such as `justify-content: center` does not work in `display: block`.
=> Styles refactored and 2 JavaScript quiz questions added

src/data/javascript-quiz.ts, src/data/linux-quiz.ts, src/data/python-quiz.ts, src/data/sql-quiz.ts
Checklist:
When my new dictionary on the spellchecker cli project is accepted then I'll add the npm package to the Quiz site.
=> Fix a few minor spelling mistakes.

src/data/linux-quiz.ts
=> Add a linux question about creating a new file

src/data/css-quiz.ts
=> Add new Css questions

src/data/linux-quiz.ts
=> Add the Linux Question about if conditions

src/data/accessibility-quiz.ts
Checklist:
Closes #XXXXX
I think it should be made clear that this question (and the link provided) refer to native mobile apps. Just using the term "mobile" could easily be interpreted as viewing a web page on a mobile device.
=> fix(question): clarify that question refers to native mobile apps

src/data/css-quiz.ts, src/data/linux-quiz.ts
=> Css question 1

src/data/git-quiz.ts
Question that allow to download objects without having to commit to the main branch. A great feature to consider when you are working on projects using different sources.
Checklist:
Closes #XXXXX
=> Added a new question about git (git fetch command)

src/data/general-cs-quiz.ts
Remove a copy of a question about OOP, two questions below we can find the same question with the same options
Checklist:
Closes #XXXXX
=> Remove duplicated question about OOP

src/data/general-cs-quiz.ts
This is a fundamental question to ensure the student understands linear running time big O notation.
Checklist:
Closes #XXXXX
=> Added a question about big O for linear time

src/data/linux-quiz.ts
Given that this is a linux question and the documentation is in linux could be better to ask about linux instead of git to avoid confusion. I wasn't able to find this command in git.
Checklist:
Closes #XXXXX
=> change git question for linux question

src/data/agile-quiz.ts
Checklist:
Adds 2 questions to #103
=> Added TDD and BDD Questions to Agile Quiz

src/data/general-cs-quiz.ts
There is duplicated question asking "What is an algorithm?" The first one is at line 557. I leave the one at line 557 because I think it has a better explanation of the concept as a set of instructions to complete a task, rather than to solve a problem.
Checklist:
Closes #XXXXX
=> Remove duplicated question "What is an Algorithm?"

src/data/general-cs-quiz.ts
This question allows evaluation of the understanding of why sorting algorithms are important, which might increase the ability of the student to learn it.
Checklist:
Closes #XXXXX
=> Question about sorting algorithms

src/data/sql-quiz.ts
I think this can help to discriminate and to show there are more options to store the same type of data.
Checklist:
Closes #XXXXX
=> Added a question about data types in SQL

src/data/general-cs-quiz.ts
=> Feature: Add a question about case styles

src/data/sql-quiz.ts
This question ask the learner understanding of different ways to store objects and also limitations of CHAR as data type in SQL
Checklist:
Closes #XXXXX
=> Question about storing characters in SQL

src/data/python-quiz.ts
There is a duplicated question about comment.  I leave the one on line 1234 because I think it has a better explanation.
Checklist: 
Closes #XXXXX
=> fix: Remove duplicate question about comment in python

src/data/python-quiz.ts
Checklist:
Closes #XXXXX
There is a duplicated question about KeyError, so I deleted the most recent. The other question is on line 1179.
=> fix: Remove duplicate question about KeyError in python

src/data/python-quiz.ts
Checklist:
Closes #XXXXX
There is a duplicated question about input(), so I deleted the most recent. 
The other question is on line 255.
=> fix: Remove duplicate question about input() in python

src/data/python-quiz.ts
Checklist:
Closes #XXXXX
There is a duplicated question about creating an empty set, so I deleted the most recent. 
The other question is on line 402.
=> fix: Remove duplicated question about set in python

src/data/javascript-quiz.ts
Cleaned up the wording about JavaScript's toFixed() method, without altering the essence of the question or its options.
closes #672
=> clean up JS question on toFixed

src/data/javascript-quiz.ts
=> updated question! for issue #671

src/data/javascript-quiz.ts
Checklist:
Updated grammar and code examples for JS arrow function question
- [+] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [+] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [+] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [+] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [+] I have provided a summary of my changes.
closes #670
=> update JS arrow function question

src/data/sql-quiz.ts
Added SQL question on 'DELETE FROM' command. The question includes a detailed explanation for educational purposes.
adds to #17
=> Add SQL delete question

src/data/quality-assurance-quiz.ts, src/data/security-quiz.ts
I have added Questions to the security & Quality Assurance Categories
=> Added security and QA questions

.github/PULL_REQUEST_TEMPLATE.md
Duplicate mention of checklist in PR template removed
closes #682
=> Removing duplicate mention of checklist in PR template

src/data/modal-responses.ts
- populated correct modal response
closes #669
=>  chore : populate correct modal response

src/data/quality-assurance-quiz.ts
I added a new question to the quality assurance quiz to enhance the content and provide more comprehensive coverage of the topic.
-  [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
=> Added a new question to qualityAssuranceQuiz

src/data/sql-quiz.ts
Added SQL question on using the 'DISTINCT' keyword to remove duplicate data. The question includes a detailed explanation for educational purposes.
adds to #17
=> Add SQL distinct question

src/data/html-quiz.ts
Removed HTML question for deprecated marquee tag
#689 
closes #689
=> Removed HTML question for deprecated marquee tag 

src/data/html-quiz.ts
updated the question on HTML checkboxes
closes #691
=> fix: update question on HTML checkboxes

src/data/agile-quiz.ts
=> chore: add agile  questions

src/data/devops-quiz.ts
Few Generic DevOps questions added.
closes #XXXXX
=> chore: Add Devops questions

src/data/accessibility-quiz.ts
=> chore: added 3 accessible questions

src/data/agile-quiz.ts, src/data/html-quiz.ts
Added 2 agile questions to quiz site.
#103
=> add: agile question

src/data/quality-assurance-quiz.ts
=> chore: add one question

src/data/accessibility-quiz.ts, src/data/devops-quiz.ts
- few generic web accessibility questions added
closes #XXXXX
=> chore: add web-accessibility que 

src/data/agile-quiz.ts
Added question for Agile quiz that contains a question about agile measure and method to measure.
Also added explanation
Added a link from freeCodeCamp regarding the question and explanation.
#103
=> Adding question on agile-quiz.ts

src/data/general-cs-quiz.ts
Added a question in general-cs quiz, the question is based on the concept of tree traversal
closes #XXXXX
=> Update general-cs-quiz.ts, Added a question on tree traversal concept

package-lock.json, package.json, src/__tests__/Results.test.tsx, src/components/Results.tsx
[Feat] Confetti Animation for Perfect Scores🚀
closes #707 
- Added the `react-confetti` dependency specifically version `^6.1.0` to the project to enable confetti animations.
- Introduced the `showConfetti` state variable to control the visibility of the `<Confetti />` component.
- When a perfect score is achieved (i.e., points === totalQuestions), the `showConfetti` state is set to true, allowing the confetti to be displayed.
- Utilized a `setTimeout` function to automatically set showConfetti back to false after 5 seconds, hiding the confetti.
- Added window size handling to make the confetti animation responsive by tracking and updating the window's width and height using the `windowSize` state variable.
=> feat: add confetti animation

src/data/accessibility-quiz.ts
Added one question in web accessibility quiz.
=> chore: added one web-accessibility question

src/data/linux-quiz.ts
=> chore: added one linux question

src/data/sql-quiz.ts
Added SQL question on the usage of the 'NEW' keyword in the context of triggers. The question includes a detailed explanation for educational purposes.
adds to #17
=> add SQL trigger question

src/data/linux-quiz.ts
Added new question regarding export command in linux-quiz.ts
Relates to #16
=> Add new question regarding export command in linux-quiz.ts

src/data/devops-quiz.ts
I've included an additional question in the DevOps quiz.
closes #XXXXX
=> chore: add devops question

src/data/sql-quiz.ts
Added a new question regarding CRUD operation in sql-quiz
Relates to #17
=> Add a question regarding CRUD operation in sql-quiz.ts

src/data/sql-quiz.ts
I've included two additional question in the SQL quiz.
closes #XXXXX
=> chore: add sql questions

src/data/cloud-computing-quiz.ts
- ## Summary of changes
chore: Added New Cloud Computing Quiz Question.
closes #XXXXX
=> new question added

src/data/agile-quiz.ts, src/data/security-quiz.ts
Added a security question
closes #104
=> Adding Security questions

src/data/devops-quiz.ts
I have added a devops question in devops-quiz.ts file in src/data
closes #XXXXX
=> Added a devops question.

src/data/sql-quiz.ts
Added SQL question about SUBSTRING_INDEX() function
closes #XXXXX
=> add SUBSTRING_INDEX SQL question

src/data/sql-quiz.ts
#17 
Contributed a new SQL question for use in the FCC Developer Quiz
=> Add new quiz question to sql-quiz.ts

src/data/linux-quiz.ts
Added a new question inside the data for linux 
closes #XXXXX
=> feat(linux): added a new question

src/data/linux-quiz.ts
* A new Question is added for Linux. 
* Updated linux-quiz.ts
- [ x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [ x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [ x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [ x] I have provided a summary of my changes.
closes #XXXXX
=> Adding New Linux Question

src/data/cloud-computing-quiz.ts
A new multiple-choice question was added.
closes #XXXXX
=> chore: a new cloud computing question added

src/data/security-quiz.ts
I've included an additional question in the Security quiz.
closes #XXXXX
=> chore: add security question

src/data/cloud-computing-quiz.ts
Added new cloud computing question.
closes #XXXXX
=> chore: cloud computing question added

src/data/accessibility-quiz.ts
1. Added a new quiz question to the codebase.
2. The new question focuses on web accessibility and the importance of the 'alt' attribute in HTML image tags.
3. Included four answer choices, one correct answer, and three distractors.
4. Provided explanations for both the correct answer and the distractors to help users understand the concepts better.
5. Added a link to an external resource for further reference on web accessibility.
These changes enhance the codebase by incorporating a new educational element related to web accessibility and image 'alt' attributes in HTML.
- [ x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x ] I have read through the [Code of …
=> chore: adding question on accessibility

src/data/accessibility-quiz.ts
I've included an additional question in the accessibility quiz.
#374
=> chore: add web-accessibility quiz

src/data/accessibility-quiz.ts, src/data/agile-quiz.ts
This PR involves updating the documentation related to Scrum. The changes made include:
1. Added a new question: "What are the three primary roles in Scrum and their key responsibilities?" along with its answer and distractors.
2. Included an explanation to clarify the purpose of the question, emphasizing its focus on Scrum roles and responsibilities.
3. Provided a link to the source for further reference.
These updates enhance the documentation by providing valuable information about Scrum roles and their responsibilities, helping users understand how Scrum operates in project management.
- [x ] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [ x] I have read through the [Code of …
=> Agile Quiz Question added

src/data/cloud-computing-quiz.ts
Update cloud-computing-quiz.ts
closes #XXXXX
=> chore: Update cloud-computing-quiz.ts

src/data/general-cs-quiz.ts
added three questions regarding AvlTree, Red-black tree and Linked list in the appropriate format.
closes #XXXXX
=> New questions added regarding DataStructures

src/data/cloud-computing-quiz.ts
Adding a question on cloud-native architecture.
closes #XXXXX
=> chore: adding a question on cloud-native architecture

src/data/regex-quiz.ts
I've included an additional question in the regex quiz.
closes #XXXXX
=> chore: add regex question

src/data/regex-quiz.ts
Added a new question.
closes #XXXXX
=> chore: adding regex question on quantifiers

src/data/general-cs-quiz.ts
added questions regarding algorithms and data structures
closes #XXXXX
=> chore: added CS questions on red-black trees

src/data/sql-quiz.ts
=> added a sql question

src/data/accessibility-quiz.ts
added  few web accessibility questions
closes #XXXXX
=> chore : add web-accessibility questions

src/data/security-quiz.ts
Added a security question that talks about how gets is vulnerable to buffer overflow attacks
closes #XXXXX
=> Added security question

src/data/accessibility-quiz.ts
This PR adds two new questions to the accessibility quiz in the `accessibility-quiz.ts` file. Each question includes multiple choices and an explanation. The questions cover topics such as the purpose of a skip navigation link, and the four broad guidelines of web accessibility. The explanations provide additional information and a link for further reading. This update enhances the quiz's content and promotes understanding of web accessibility principles.
closes #XXXXX
=> chore: add web accessibily questions

src/data/general-cs-quiz.ts, src/data/sql-quiz.ts
I have added Some good level Cs fundamental question 
#29 
closes #XXXXX
=> Added Computer Science Quiz Question

src/data/general-cs-quiz.ts
=> Added a computer science question

src/data/cloud-computing-quiz.ts
Adding questions on serverless computing.
closes #XXXXX
=> chore: adding questions on serverless computing.

src/data/agile-quiz.ts
Add questions on Agile.
closes #XXXXX
=> chore: add agile questions

src/data/agile-quiz.ts, src/data/general-cs-quiz.ts
Added a Priority queue question in the general-cs-quiz.ts stating the definition of priority queue
=> updated general-cs-quiz.ts with priority queue question

src/data/sql-quiz.ts
Added a question about SQL injections
closes #XXXXX
=> Chore: Added a SQL question

src/data/linux-quiz.ts
I have added some good level of linux quiz questions
#16
=> Added Linux Quiz Questions

src/data/quality-assurance-quiz.ts
Add quality assurance questions
closes #XXXXX
=> chore: add quality assurance questions

src/data/cloud-computing-quiz.ts
Adding questions on cloud computing service models.
closes #XXXXX
=> chore: adding questions on cloud computing service models

src/data/agile-quiz.ts
- Added Agile questions relating to the following sub-topics:
-  Behavioral Driven Development
- Acceptance Criteria
- Daily Standup
- This PR is in relation to #103
=> added 3 agile questions relating to bdd, acceptance criteria, and daily standup

src/data/quality-assurance-quiz.ts
- Added QA Testing questions:
Cross-Browser Compatibility Testing
This PR is in relation to issue https://github.com/freeCodeCamp/Developer_Quiz_Site/issues/102
=> Addition of 2 QA questions

src/data/linux-quiz.ts
Added a question about how linux work on ubuntu
=> In linux-quiz.ts added a question related to linux kernels

src/data/general-cs-quiz.ts
added a few general computer science questions
closes #XXXXX
=> chore: add computer science questions

src/data/sql-quiz.ts
I have added 5 new question in sql section of the quiz.
- [ x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [ x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [ x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [ x] I have provided a summary of my changes.
closes #XXXXX
=> Adding 5 new Sql questions

src/data/accessibility-quiz.ts
Added 14 more accessibility quiz question whilst making sure that none of them existed already in the questionaire.
closes #XXXXX
=> added more accessibility quiz questions

src/data/cloud-computing-quiz.ts
Adding questions on cloud storage
closes #XXXXX
=> chore: adding questions on cloud storage

src/data/quality-assurance-quiz.ts
added a few quality assurance questions
closes #XXXXX
=> chore: add quality-assurance questions

src/data/general-cs-quiz.ts
Added questions to generalcsquiz
closes #XXXXX
=> Added-questions-to-generalcsquiz

src/data/accessibility-quiz.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1vaxYS4Tt0bnIxJieMFAdGdPYYkQXQQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=ivdmUgZ)
Fixed a few grammar errors and added a web accessibility question.
I made a few spelling and grammar changes to some of the quiz questions and also added one web accessibility examples question.
closes #XXXXX
=> Add accessibility example question to accessibility-quiz.ts

src/data/quality-assurance-quiz.ts
Added 8 new testing ques in https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/quality-assurance-quiz.ts
closes #XXXXX
=> adding-new-qa&testing-ques

src/data/html-quiz.ts
Added questions to html quiz
closes #XXXXX
=> Added questions to html-quiz

src/data/cloud-computing-quiz.ts
Adding questions on file storage options in cloud computing.
closes #XXXXX
=> chore: adding questions on file storage options in cloud computing

src/data/linux-quiz.ts
Added Debain related question in linux quiz
closes #XXXXX
=> Added Debain related question in linux quiz

src/data/accessibility-quiz.ts
Added a quiz about relative unit and absolute measurement to accessibilityQuiz.
#374
=> Added a quiz about relative unit to accessibilityQuiz

src/data/javascript-quiz.ts
adding a macrotask quiz question in javascript
closes #XXXXX
=> adding a macrotask quiz question in javascript

src/data/sql-quiz.ts
Added 9 more sql ques in sqlQuiz array.
closes #XXXXX
=> added 9 new sql questions

src/data/css-quiz.ts
Added spacing related question in CSS quiz
closes #XXXXX
=> Added spacing related question in CSS quiz

src/data/javascript-quiz.ts, src/data/linux-quiz.ts
A Linux quiz question was added referring to the command `halt`
- [x ] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x ] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x ] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x ] I have provided a summary of my changes.
closes #XXXXX
=> Linux command quiz new question

src/data/cloud-computing-quiz.ts
Adding questions on cloud-native applications
closes #XXXXX
=> chore: adding questions on cloud-native applications

src/data/accessibility-quiz.ts
- Included a set of web accessibility questions in the `accessibility-questions.md` file.
closes #XXXXX
=> Added some web accessibility questions

src/data/general-cs-quiz.ts
Added a question to the general-cs-quiz.ts file.
#29
=> Added a question to general-cs-quiz.ts

src/data/sql-quiz.ts
add a sql question to quiz users's knowledge on quering dates selections
closes #XXXXX
=> add a sql question to quiz users's knowledge on quering dates selections

src/data/javascript-quiz.ts
add a javascript question quizing users's knowledge on async await
closes #XXXXX
=> add a javascript question quizing users's knowledge on async await

src/data/regex-quiz.ts
I added 5 questions on the lookarounds and one on regex groups
closes #XXXXX
=> add regex questions

src/data/sql-quiz.ts
Added 3 questions to the SQL Quiz on WHERE clause, AND logical operator, and UNIQUE constraint. Those 3 questions are added at the end of the sqlQuiz array.
closes #XXXXX
=> Added questions to sql-quiz.ts

src/data/accessibility-quiz.ts
question about licensed software of screen reader for windows.
=> Added Screen Reader application question to Accessibility-quiz.ts

src/data/accessibility-quiz.ts
I added a question for the accessibility quiz regarding color in graph to convey meaning.
closes #XXXXX
=> add accessibiliy question about color in graph

src/data/cloud-computing-quiz.ts
Adding a question on cloud-native applications.
closes #XXXXX
=> chore: adding a question on cloud-native applications.

src/data/security-quiz.ts
Added three quiz questions to the security quiz. they were on the CIA triad, I looked through the available questions and saw there was none on the CIA triad.
closes #XXXXX
=> security quiz questions on the CIA Triad

src/data/sql-quiz.ts
I have added two postgresql questions and successfully tested them with the documentation links locally.
One question was about the syntax for deleting a database and the other was about the default port number.
closes #XXXXX
=> add postgresql questions

src/data/sql-quiz.ts
Added two new question types to SQL quiz. 'What is the difference between CHAR and VARCHAR data types in SQL?' and 'What is the difference between data types NUMERIC and FLOAT in SQL?'
- [ x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [ x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x ] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [ x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x ] I have provided a summary of my changes.
closes #XXXXX
=> chore: adding SQL questions

src/data/cloud-computing-quiz.ts
Adding a question on cloud-native applications
closes #XXXXX
=> chore: adding a question on cloud-native applications

src/components/Questions.tsx, src/components/QuizTemplate.tsx, src/stylesheets/App.css
I've implemented the changes talked about in #850 but it seems I created another bug; the questions now reshuffle every time you select an option.
I've found the code causing it but I can't seem to solve it. I am fairly new to react so I'm not too conversant with how react handles re-rendering on state changes so I think I'll need some help on this one.
closes #850
=> feat: updating flow for submitting answers

src/data/accessibility-quiz.ts
Added 3 accessibility to accessibilityQuiz
closes #XXXXX
=> add 3 accessibility questions

src/data/sql-quiz.ts
Added Sql Questions onTemporary Tables in Sql
- [x ] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [ x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x ] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [ x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [ x] I have provided a summary of my changes.
closes #XXXXX
=> Added Sql Questions

src/data/javascript-quiz.ts
This PR adds a question to the JavaScript quiz on objects and primitive values.
=> Add JavaScript Question on Objects and Primitive values

src/data/accessibility-quiz.ts
A [PR was opened for this one and closed by maintainers](https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/877) because it was a yes/no question which should be avoided for the quiz section. 
I updated the question and answers on the `<main>` landmark to make it an open question.
closes #XXXXX
=> A11y question on <main> landmark

src/data/accessibility-quiz.ts
I added a question to the a11y quiz section regarding which one of the provided examples is not a corresponding role landmark.
closes #XXXXX
=> A11y Quiz: HTML5 corresponding landmark question

src/data/agile-quiz.ts
Add five questions to agileQuiz.ts
closes #XXXXX
=> add five questions to agile-quiz.ts

src/data/javascript-quiz.ts, src/data/python-quiz.ts
The PR adds a question in the Python quiz about dunder methods.
=> Add Python question on Dunder methods

src/data/general-cs-quiz.ts
=> add LLD ques

src/data/linux-quiz.ts
#16 
Contributed a new question about Linux for use in the FCC Developer Quiz.
=> Add new linux quiz question to linux-quiz.ts

src/data/linux-quiz.ts
src/data/linux-quiz.ts
closes #XXXXX
=> add 16 questions to src/data/linux-quiz.ts 

src/data/quality-assurance-quiz.ts
- Added 4 questions to the qa/testing file
- related to #102
=> Added 4 questions to the  quality-assurance-quiz.ts file

src/data/sql-quiz.ts
=> add new sql question(s)

src/data/sql-quiz.ts
add 9 questions to sql-quiz.ts
closes #XXXXX
=> add 9 questions to sql-quiz.ts

src/data/agile-quiz.ts
- Added 4 agile questions in relation to burndown/burnup charts and non-functional requirements
- Issue #103 
closes #XXXXX
=> added 4 agile questions to agile-quiz.ts

src/data/general-cs-quiz.ts
=> chore: adding question on New Technology File System

src/data/sql-quiz.ts
Added an SQL operator question to sql-quiz.ts
closes #XXXXX
=> Adding SQL quiz questions #17 - Added SQL operator Question

src/data/modal-responses.ts
- [x ] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x ] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x ] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [ x] I have provided a summary of my changes.
closes #795
=> feat: Add 10 more incorrect responses to quiz modal

src/data/general-cs-quiz.ts
Added Computer Science Questions
=> chore: adding question for computer vision to cs quiz

src/data/accessibility-quiz.ts
Add six more questions in the beginner-friendly accessibility questions.
Mentioned in issue #899
closes #XXXXX
=> Add beginner friendly accessibility questions

src/data/css-quiz.ts, src/data/javascript-quiz.ts, src/data/python-quiz.ts
This PR adds a question to the CSS quiz on font faces.
=> Add CSS Question on font faces

src/data/accessibility-quiz.ts
Adding five more beginner-friendly accessibility questions mentioned in Issue #899 
closes #XXXXX
=> Adding beginner friendly accessibility questions

README.md
Added a contributors section displaying all the contributors for the project.
Screenshot preview:
=> Added contributors section

src/data/linux-quiz.ts
=> add new linux question(s)

src/data/linux-quiz.ts
Added Linux question on the `chroot` command. The question includes a detailed explanation for educational purposes.
adds to #16
=> Add chroot Linux question

src/data/accessibility-quiz.ts
Adding accessibility questions mentioned in Issue https://github.com/freeCodeCamp/Developer_Quiz_Site/issues/899
#899
=> chore: add some more questions and answers to the Accessbility Quiz

src/data/javascript-quiz.ts
This PR adds a question to the JavaScript quiz on string concatenation.
=> Add JavaScript Question on String Concatenation

src/data/accessibility-quiz.ts
Added a single important & fundamental question for understanding web accessibility comprehensively for beginners & professionals alike.
=> chore: adding question for accessibility quiz 

src/data/general-cs-quiz.ts
Added questions for one of the most important concept i.e. Recursion.
=> Update general-cs-quiz.ts #3

src/data/sql-quiz.ts
Added a question regarding normal forms to SQL Quiz file
closes #XXXXX
=> Added a question regarding normal forms

src/data/javascript-quiz.ts
This PR adds a question to the JavaScritp Quiz on valid variable names
=> Add JS Question on Valid Variable Names

src/stylesheets/App.css
add `glowing` effect when hover above the buttons
https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/1336862/449b85ae-39ec-4983-989f-35cbcd1d15da
closes #924
=> feat: add glowing effect when hovering above buttons

index.html, src/__tests__/App.test.tsx, src/__tests__/WelcomePage.test.tsx, vite.config.ts
i saw that after my recent changes the tests are broken,
so i did some fixes to make them run
also, (for solve the `creation of results.json file in node_modules inside src` bug) i moved index file to be at the root instead of being inside `src`  
closes #XXXXX
=> test: make the App & Welcome tests pass

src/__tests__/App.test.tsx, src/__tests__/WelcomePage.test.tsx, src/index.tsx
suppose to solve `refresh browser` problem
closes #939
=> fix: replace browserRouter by hashRouter

src/components/Questions.tsx, src/components/QuizTemplate.tsx
=> feat: use routes at inner pages

src/data/linux-quiz.ts
I have added a linux question about opening and closing of a file in `vim` editor and added the changes to `src/data/linux-quiz.ts`.
Issue - #16
=> Added linux questions

src/__tests__/SelectCategory.test.tsx, src/components/QuizTemplate.tsx, src/components/SelectCategory.tsx, src/components/SelectQuestionsTotal.tsx, src/constants.ts
changing some component properties to be taken from `constants`, and also rename them
selectCategoriesArr -> CATEGORIES
closes #XXXXX
=> chore: move categoriesArr and questionsNumArr to constants

.github/workflows/react-tests.yml
This adds a Github workflow that is supposed to execute every time a pull request or push is made that installs all of the dependencies and then runs all of the tests. 
closes #937
=> chore: create a test workflow

.npmrc
closes #955
https://github.com/pnpm/pnpm/issues/2891
I think it's possible we were just using a slightly outdated version of `pnpm` because this issue was solved in version 9 of `pnpm`. Regardless I have enabled-pre-post scripts and everything seems to have been fixed. I have it working just fine in my branch as well.
=> fix: restore git page deployment

package.json, pnpm-lock.yaml, vite.config.ts
=> chore: add `happy-dom` as tests environment

src/data/accessibility-quiz.ts
Added new beginner-friendly accessibility questions to the accessibility quiz data file to expand the current collection.
closes #XXXXX
=> Added beginner friendly accessibility questions

package.json, pnpm-lock.yaml
=> chore: upgrade typescript to 5 version

src/data/python-quiz.ts
I added unique questions to the python quiz in the file 'python-quiz.ts'
[x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
[x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
[x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
[x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
[x] I have provided a summary of my changes.
=> Added a new question in Python quiz on topic 'Decorators'

.dockerignore, CONTRIBUTING.md, Dockerfile, README.md, docker-compose.yml, vite.config.ts
- Missing global pnpm in the image
- Inconsistent BASE_TAG defined in the `Dockerfile` 
- process exit error : [ref](https://github.com/codesandbox/codesandbox-client/issues/6642)
closes #970
=> Fix: Container issue  

src/data/general-cs-quiz.ts, src/data/information-technology-quiz.ts
I added unique questions to the information Technology quiz
closes #XXXXX
=> feat: adding questions for information Technology quiz

src/data/general-cs-quiz.ts
I added unique questions to the list of General CS Quiz, questions on DNS, firewall, OOP, encapsulation and polymorphism
closes #XXXXX
=> feat: adding questions for General CS Quiz

src/data/javascript-quiz.ts
Added 3 JavaScript question to the quiz
- [ x ] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [ x ] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [ x ] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [ x ] I have provided a summary of my changes.
=> add: Added 3 new questions to the JavaScript quiz

src/data/git-quiz.ts, src/data/sql-quiz.ts
=> adding question to the git quiz

src/data/accessibility-quiz.ts
- Added 2 accessibility questions in the specified format.
- Each question includes multiple choice options with one correct answer and an explanation.
closes #899
=> [Feat] Add 2 Beginner Friendly Accessibility Questions (#899)

package.json, src/__tests__/App.test.tsx, src/__tests__/Data.test.tsx, src/__tests__/Results.test.tsx, src/__tests__/SelectCategory.test.tsx, src/__tests__/SelectQuestionsTotal.test.tsx, src/__tests__/WelcomePage.test.tsx
This updates all the tests to have proper imports present so there will be no red squiggly lines. This also updates the cli for fix style script so that it will actually be able to work.  Previously it would be unable to find any files to fix. 
closes #1033
=> fix: update tests to define vitest functions

src/stylesheets/ButtonLink.css
closes #1017
This is a really simple fix.
=> fix(UI): align started text

src/data/quality-assurance-quiz.ts
Added a question to the quality-assurance-quiz.ts file. 
refer to issue #102
=> Add 1 question to QA quiz

src/data/linux-quiz.ts
=> Added two linux questions

src/data/security-quiz.ts
Added three new question related to security from the freecodecamp articles.
closes #XXXXX
=> Added new Security Quiz Questions

tsconfig.app.json, tsconfig.json, tsconfig.node.json
=> chore: split tsconfig into app and node json files

src/data/git-quiz.ts
I added a question concerning the pros and cons of using the git stash command.
=> Add git stash question to Git Quiz

e2e/can-run-quiz.spec.ts, src/components/Questions.tsx, src/components/QuizTemplate.tsx
=> refactor: change selectOption method to use choice string

src/data/sql-quiz.ts
Added SQL Quiz Question in #17 Please Merge as soon as possible
- [✓] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [✓] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [✓] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [✓] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [✓] I have provided a summary of my changes.
closes #XXXXX
=> Added SQL Quiz Question

src/data/information-technology-quiz.ts
=> feat: adding question for information-technology-quiz

src/data/security-quiz.ts
=> feat: add security question

src/data/general-cs-quiz.ts, src/data/sql-quiz.ts
I added a general CS quiz question and want to contribute in #29
- [✓] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [✓] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [✓] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [✓] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [✓] I have provided a summary of my changes.
closes #XXXXX
=> Added General CS Quiz Question

src/data/security-quiz.ts
Added a set of security-related multiple-choice questions to the security-quiz.ts file. The questions are from cloud cyber security.
related to #1135
=> Added some questions to security-quiz.ts related to cloud computing secutity

src/data/agile-quiz.ts, src/data/general-cs-quiz.ts
=> feat: adding question for agile quiz

src/components/QuizTemplate.tsx, src/components/SelectQuestionsTotal.tsx
=> refactor: some unused props can be removed

src/data/sql-quiz.ts
This PR adds a new question to the SQL category, focusing on the representation of entities in an ERD (Entity Relationship Diagram). The question asks about the common shape used to represent entities and tables in an ERD, with an explanation that highlights the use of rectangles to contain the entity name.
=> Add ERD question on entity representation in SQL category

src/components/Questions.tsx, src/components/QuizTemplate.tsx
=> refactor: answerButtonsRef can be removed

src/data/security-quiz.ts
Added a question related to security to the security-quiz.ts file.
Address part of #1135
=> Adding security question for quiz

src/data/linux-quiz.ts
Add 'userdel" command question
=> add-new-linux-quiz-question

src/data/linux-quiz.ts
Add a linux quiz question for what is a Daemon
Issue #16
=> chore: add linux question on daemon

index.html, src/stylesheets/App.css, src/stylesheets/Modal.css
=> chore: remove bootstrap links at index.html

src/components/Button.tsx, src/components/ButtonLink.tsx, src/components/Questions.tsx, src/components/QuizModal.tsx, src/components/Results.tsx, src/components/SelectCategory.tsx, src/components/SelectQuestionsTotal.tsx, src/types.tsx
+ Extracted all TypeScript interfaces from component files into a single common types file.
+ Ensured that the interfaces are reusable and easy to find by centralizing them.
+ Organized and streamlined the codebase for better maintainability and scalability.
closes #1216
=> chore: move interfaces to types file

e2e/can-finish-quiz.spec.ts
=> fix(e2e): improve test description and add some comments
