- src/data/full-quiz.js
Apple OS doesn't exists. As of December 2021, Apple is the vendor of
macOS, iOS, iPadOS, watchOS and tvOS.
Checklist:
---
Seems like [the linked article](https://www.freecodecamp.org/news/what-is-a-pc-computer-definition-and-computer-basics-for-beginners/#:~:text=The%20most%20popular%20operating%20systems%20commonly%20used%20today%20are%20Microsoft%27s%20Windows%20OS%20and%20Apple%20OS.%20Linux%20is%20also%20a%20very%20popular%20operating%20system%20among%20developers.) has to be updated too. How can I update it?
> fix(quiz): replace Apple OS with macOS

- src/components/Results.jsx
In the result view, there is a space before the "RPG game" link. It's not looking good, because the underline is shown in space, and it looks like "_RPG game". So I removed a space from the start of <a> tag and added a space at end of <p> tag, and It looks fine :)
Checklist:
> Remove extra space in the "RPG game" link.

- src/components/Results.jsx
Checklist:
Results page looks like it needs a space. I've also added a semi-colon as well. Results aren't tested live, but looks like it should work based on [this tutorial](https://techstacker.com/how-to-add-white-space-between-elements-react-jsx/).
Currently:
Update:
> Add non-breaking white space for results page

- README.md
Checklist:
Thought it would be easier for contributors to find where the data lives by putting it directly in the README.md.
> Add direct link to where quiz data lives

- src/data/full-quiz.ts
I updated the HTML abbreviation question.
The old incorrect answer: Hyper Text Markup Language
New correct answer: HyperText Markup Language
Checklist:
> fix: html abbreviation question in full-quiz.ts file

- src/data/full-quiz.ts
The distractor answers should be plural like the real answer. This
commit also adds some context for some confusion around this acronym.
Checklist:
Closes #XXXXX
> chore: add plural form of words and add nuance

- src/components/Questions.tsx
- src/components/QuizModal.tsx
- src/components/QuizTemplate.tsx
This adds a property to the Quiz Question modal that gets passed around. It currently adds the chosen answer to both wrong and correct answers but it probably is okay. 
Checklist:
Closes #74
> Add the chosen answer field to the results

- src/components/HeroSection.tsx
- src/components/WelcomePage.tsx
- src/stylesheets/HomepageRow.css
Reducing content in homepage sections to resolve text overlapping issue for browsers set to large or extra large font sizes. 
Checklist:
Closes #85
> fix: reducing content to fix browser font size issue

- src/data/full-quiz.ts
> Adding a CS question in full-quiz.js

- src/data/sql-quiz.ts
> feat: Added a new SQL question (DROP TABLE)

- src/data/python-quiz.ts
Checklist:
Closes #XXXXX
This question was good, but the options were so easy that anyone would guess that the correct answer is 4 only, I changed the distractors to 2,6,8 , now the question look even thinkable than before.
> chore: changing distractor answers for python indentation question

- src/data/general-cs-quiz.ts
Checklist:
Adds to #29 
Question asks about definition of subnet.
> add general cs quiz question

- src/stylesheets/App.css
- [ x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)
Added padding right and padding left for quiz text (question) shown on the screen, since the question was taking up 100% of screen width.
> Padding Left and Right for Quiz Text(Question)

- src/components/WelcomePage.tsx
- src/stylesheets/Button.css
- src/stylesheets/HomepageRow.css
Checklist:
Closes #176 
- Added a media query to the Get started button for mobile devices
-  Added an inline style to set the margin to 0 for the class 'row' which stops the problem of the 'row' class having a default margin of -12px
-  Added a 100vw width to the class 'content-row-container' so that it does exceed the screen width
> Fix: Added a media query to the button and removed extra margins from rows

- src/data/python-quiz.ts
> Added one question regarding python list slicing in python-quiz.ts

- src/data/accessibility-quiz.ts
Checklist:
Closes #XXXXX
The `section` element does not provide any enhanced accessibility by default. Unless you manually give it an accessible name using either the `aria-label` or `aria-labelledby` attributes it is basically the same as using a `div`. The `main` element would be a much better example to use here as it creates a main landmark by default and every page should have one.
> fix(question): replace section element with main element in accessibility quiz

- src/data/accessibility-quiz.ts
Checklist:
Closes #XXXXX
Skip links are primarily for keyboard users, which of course does include most screen reader users. But I think the focus of this question should be about increasing the accessibility for keyboard users in general since most people using a keyboard will not be using a screen reader.
> fix(question): update a11y quiz skip link question

- package-lock.json
- src/__tests__/Results.test.tsx
- src/__tests__/SelectCategory.test.tsx
- src/__tests__/SelectQuiz.test.tsx
- src/components/Questions.tsx
- src/components/QuizTemplate.tsx
- src/components/Results.tsx
- src/components/SelectCategory.tsx
- src/components/SelectQuiz.tsx
- src/constants.ts
- src/data/agile-quiz.ts
- src/data/css-quiz.ts
- src/data/git-quiz.ts
- src/data/quality-assurance-quiz.ts
- src/data/sql-quiz.ts
Checklist:
Closes #657 
This PR adds the SelectCategory component, which allows users to choose a category for the quiz. It also moves the array of categories to `QuizTemplate` for better organization. After selecting a category, the quiz number is displayed. 
The conditional rendering of questions has been reorganized to ensure they are only rendered after selecting a number. Constants have been reworked for improved readability. The filtered category is now used to start the quiz. 
Tests have been added to ensure the component renders and displays options.
_Generated using [OpenSauced](https://opensauced.ai/)._
> feature: add category choice to quiz

- src/data/javascript-quiz.ts
Checklist:
Removed duplicate quiz question bug in the JavaScript module.
closes #679
> fix: remove duplicate JS quiz question 

- src/data/javascript-quiz.ts
Summary 
I Have added a new and one of most important question asked in JavaScript based interviews that is IIFE .
The Question is added to the javascript-quiz.ts file .
The main use of IIFE is to create a private variable and the same is being discussed with the question provided .
> New Javascript Question added based on IIFE

- src/data/sql-quiz.ts
> Added a new SQL question

- src/data/accessibility-quiz.ts
This PR adds questions about some ARIAs and best practices to the accessibility quiz. 
Relates to #374
> feat: add questions about some ARIA roles and best practices to accessibility quiz

- src/data/accessibility-quiz.ts
Related to #374 
Added a new web accessibility quiz question on cognitive accessibility.
Question:
"In the context of web accessibility, what does 'cognitive accessibility' refer to?",
Answer: "Ensuring that web content is easy to understand and use for individuals with cognitive disabilities.",
Distractor1: "Making web content more engaging and interactive.",
Distractor2: "Enhancing the creativity and aesthetics of web design.",
Distractor3: "Providing audio descriptions for video content.",
Explanation:
"'Cognitive accessibility' refers to the practice of designing and structuring web content in a way that makes it easy to comprehend and navigate for individuals with cognitive disabilities like dyslexia, attention deficit disorders, or intellectual disabilities.",
Link: …
> Web Accessibility Quiz Question

- src/data/accessibility-quiz.ts
This PR replace a duplicate question (which already exist in line number 346 -356) with a new one regarding rel attribute in accessibility quiz.
Relates to #374
> Add a question regarding rel attribute in accessibility quiz.ts

- src/data/sql-quiz.ts
#17 
* contributed new SQL questions for use in the FCC Developer Quiz
> added new sql quiz questions

- src/stylesheets/App.css
A media query was added to the App.css file that sets the width of .select-btn-div to auto, this fixes the issue of text over flow on smaller screen sizes.
closes #747
> Add media query to stop button overflow

- src/data/accessibility-quiz.ts
For the a11y quiz I created a question regarding the counterpart of the default landmark complementary when using semantic HTML.
closes #XXXXX
> A11y-Quiz: default landmark complementary counterpart

- src/components/Questions.tsx
- src/stylesheets/App.css
The current layout of the quiz container, which displays the question, options, and submit button, utilizes the `w-50` class for a 50% width. While this approach works well on larger screens, it presents usability challenges on mobile devices due to their limited screen real estate.
**Implementation**
- Removed the `w-50` class from the quiz container.
- Added a media query targeting devices with screen widths less than `460px`. Within this rule, the container's width is set to 100%, ensuring it occupies the full width of the mobile screen and improves user experience.
**Attached full screenshot showing after changing the width to `100%` in mobile devices**
closes #926
> fix: Responsive Layout Enhancement for Quiz Container

- src/components/Questions.tsx
prevent 404 from appear when refreshing browser
closes #939
> fix: refresh browser should navigate to quizzes page

- src/components/QuizTemplate.tsx
- src/components/SelectQuestionsTotal.tsx
when selecting total-questions-of-quiz - better to pass number instead of passing mouse event
closes #XXXXX
> refactor: when selecting total-questions-of-quiz - better to pass number

- src/stylesheets/App.css
This PR sets the selected answer color as goldenrod and set the other button colors to lime. I think at some point we should consider adding a dark mode toggle but there's no rush. 
closes #965
> feat(UI): make selected answer pop

- src/components/QuizTemplate.tsx
- src/components/SelectCategory.tsx
This removes the event handler defined in the `SelectCategoryProps` properties as per the instructions. I have tested the codebase and everything seems fine. 
closes #1039
> fix: remove unused event handler

- src/__tests__/SelectCategory.test.tsx
- src/components/QuizTemplate.tsx
- src/components/SelectCategory.tsx
since the purpose of this component is - to select categories   
looks like this method not used anywhere at app, and was copied to this component by mistake...
closes #XXXXX
> refactor: remove selectQuizNumber prop form selectCategory component

- src/components/Questions.tsx
Fixed the bug in Question.tsx it was missing correct(boolean) field
- [✅ ] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [✅ ] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [ ✅] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [ ✅] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [ ✅] I have provided a summary of my changes.
closes #1151
> fix: add missing 'correct' field to QuizQuestion interface to remove the bug in QuizModalProps

- src/stylesheets/App.css
- src/stylesheets/HeroSection.css
- src/stylesheets/HomepageRow.css
- src/stylesheets/Navbar.css
This makes the height of the row container grow and shrink relative to the screen height rather than use fixed height when zoomed in. I also updated some of the units to be `rem` instead of `px`. 
closes #1280
> fix(ui): use percentages for content row container height
